services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: ewket-tutor-chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ALLOW_RESET=true
    volumes:
      - ./data/chroma:/chroma/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ewket-tutor-backend
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    depends_on:
      chromadb:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: always
