version: "3.9"

services:
  database:
    image: postgres:15
    container_name: ewket-tutor-db
    environment:
      POSTGRES_USER: ewket
      POSTGRES_PASSWORD: ewket123
      POSTGRES_DB: ewket_tutor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: ewket-tutor-chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ALLOW_RESET=true
    volumes:
      - ./data/chroma:/chroma/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ewket-tutor-backend
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - DATABASE_URL=postgresql://ewket:ewket123@database:5432/ewket_tutor
    depends_on:
      - database
      - chromadb
    volumes:
      - ./backend:/app
      - ./backend/data/uploads:/app/data/uploads
    restart: always

  student-web:
    build: ./student/web
    container_name: ewket-student-web
    depends_on:
      - backend
    ports:
      - "3001:3000"

  admin-web:
    build: ./admin/web
    container_name: ewket-admin-web
    depends_on:
      - backend
    ports:
      - "3002:3000"

volumes:
  postgres_data:


