version: "3.9"

services:
  database:
    image: postgres:15
    container_name: ewket-tutor-db
    environment:
      POSTGRES_USER: ewket
      POSTGRES_PASSWORD: ewket123
      POSTGRES_DB: ewket_tutor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: ewket-tutor-chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ALLOW_RESET=true
    volumes:
      - ./data/chroma:/chroma/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: always


volumes:
  postgres_data:


